name: "Clean Packages"

on:
  workflow_call:

  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: "Clean Old Ratatosk.Abstractions Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Abstractions'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: "true"

      - name: "Clean Old Ratatosk.Connector.Abstractions Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Connector.Abstractions'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: "true"

      - name: "Clean Old Ratatosk.Telegram Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Telegram'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: true

      - name: "Clean Old Ratatosk.Sendgrid Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Sendgrid'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: true

      - name: "Clean Old Ratatosk.Firebase Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Firebase'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: true

      - name: "Clean Old Ratatosk.Facebook Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Facebook'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: true

      - name: "Clean Old Ratatosk.Twilio Nuget Packages"
        uses: actions/delete-package-versions@v4
        with:
          package-name: 'Ratatosk.Twilio'
          package-type: 'nuget'
          min-versions-to-keep: 15
          delete-only-pre-release-versions: true
